============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/runner/work/pyMayCoor/pyMayCoor
plugins: cov-4.0.0
collected 52 items

test/test_calculations.py ..................
test/test_calculations_for_atoms_lists.py ................
test/test_end_to_end.py /tmp/pytest-of-runner/pytest-0/data0
F
test/test_input_data.py .................

=================================== FAILURES ===================================
_____________________ TestEndToEnd.test_execute_app_in_cmd _____________________

self = <test.test_end_to_end.TestEndToEnd object at 0x7fc898870af0>
env_for_end_to_end_tests = PosixPath('/tmp/pytest-of-runner/pytest-0/data0')

    @pytest.mark.usefixtures("env_for_end_to_end_tests")
    def test_execute_app_in_cmd(self, env_for_end_to_end_tests):
        print(env_for_end_to_end_tests)
        fn = env_for_end_to_end_tests / 'output.txt'
    
        subprocess.run(
            f'python3_10 ./main/main.py -i ./egzamples_instructions/out1.txt -s ./egzamples_instructions/settings.yaml -o "{str(fn)}"', shell=True)
    
>       with open(fn, 'r', encoding="utf-8") as file:
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-runner/pytest-0/data0/output.txt'

test/test_end_to_end.py:14: FileNotFoundError
=============================== warnings summary ===============================
test/test_calculations_for_atoms_lists.py:168
  /home/runner/work/pyMayCoor/pyMayCoor/test/test_calculations_for_atoms_lists.py:168: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.slow

test/test_calculations_for_atoms_lists.py:182
  /home/runner/work/pyMayCoor/pyMayCoor/test/test_calculations_for_atoms_lists.py:182: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.slow

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
----- generated xml file: /home/runner/work/pyMayCoor/pyMayCoor/pytest.xml -----

---------- coverage: platform linux, python 3.10.6-final-0 -----------
Name                                                                             Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------------------------
main/BondOrderProcessing/bond_order_processing/calculations.py                     352      9    97%   40, 44, 51, 171, 324, 505, 660, 662-663
main/BondOrderProcessing/bond_order_processing/calculations_for_atoms_lists.py     166      3    98%   84-87
main/BondOrderProcessing/bond_order_processing/input_data.py                       418     53    87%   88-100, 122-155, 185-189, 225, 234-238, 306, 319-320, 373-377, 424-435, 472-473, 479, 494, 501, 658, 665, 703, 732, 736, 759, 766, 812, 820, 866, 872, 886, 937, 949
--------------------------------------------------------------------------------------------------------------
TOTAL                                                                              937     65    93%

1 file skipped due to complete coverage.

=========================== short test summary info ============================
FAILED test/test_end_to_end.py::TestEndToEnd::test_execute_app_in_cmd - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-runner/pytest-0/data0/output.txt'
================== 1 failed, 51 passed, 2 warnings in 19.39s ===================
